apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: gestor-versao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "vr"
            - name: RABBITMQ_DEFAULT_PASS
              value: "vr!RbtMQ"
