apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: gestor-versao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672 # RabbitMQ port
            - containerPort: 15672 # Management UI port
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "vr@Rabbit1!"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: gestor-versao
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
